name: 🚀 Enterprise DevSecOps Pipeline

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  # TẦNG 1: QUÉT MẬT KHẨU (SECRET SCANNING)
  security-scan:
    name: Quét Lỗ Hổng Mật Khẩu 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Chạy Gitleaks Scan thực tế
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # TẦNG 2: KIỂM THỬ CHỨC NĂNG (UNIT TEST)
  unit-test:
    name: Kiểm Thử Logic (Vitest)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Cài đặt thư viện
        run: npm install
      - name: Chạy Unit Test
        run: npm test

  # TẦNG 3: QUÉT LỖ HỔNG THƯ VIỆN (SCA)
  dependency-audit:
    name: NPM Audit (Lỗ hổng thư viện)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm audit --audit-level=critical

  # TẦNG 4: QUÉT MÃ NGUỒN TĨNH (SAST) - CODEQL
  sast-codeql:
    name: CodeQL (Phân Tích Cú Pháp)
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  # TẦNG 5 & 6: BẢO MẬT HẠ TẦNG (DAST & CONTAINER)
  # container-security:
  #   name: 🐳 Trivy (Quét Lỗ Hổng Docker)
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Build an image from Dockerfile
  #       run: docker build -t my-payment-service:${{ github.sha }} .
  #     - name: Run Trivy vulnerability scanner
  #       uses: aquasecurity/trivy-action@master
  #       with:
  #         image-ref: 'my-payment-service:${{ github.sha }}'
  #         format: 'table'
  #         exit-code: '1' # Đánh sập pipeline nếu phát hiện lỗ hổng OS/Thư viện
  #         severity: 'CRITICAL,HIGH'